# Generated by Django 3.1.2 on 2023-05-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230507_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='vencimineto',
            new_name='vencimiento',
        ),
    ]
