# Generated by Django 3.1.2 on 2023-05-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230507_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='vencimiento',
        ),
    ]
