# Generated by Django 3.1.2 on 2023-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230520_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposproductos',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
