# Generated by Django 3.1.2 on 2023-05-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_empleado_historial_subscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombreCli',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nombreEmp',
        ),
        migrations.RemoveField(
            model_name='subscripcion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='subscripcion',
            name='nombre',
        ),
    ]
