# Generated by Django 3.1.2 on 2023-05-21 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230520_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripcion',
            name='nombreSubs',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscripcion',
            name='rut',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
